SELECT INS_ID,  
INS_NAME, 
INS_EMAIL, 
INS_PHONE, 
INS_BIRTH, 
INS_PROFILE, 
INS_AUTH,  
INS_RATING, 
INS_CARRER, 
INS_BANKNUM, 
INS_BANK, 
INS_REGDATE, 
c.CAR_FILE ,
c.CAR_DEPART ,
c.CAR_POSITION ,
c.CAR_PERIOD ,
c.CAR_CONTENT 
INS_DELFLAG FROM INSTRUCTOR i JOIN CAREER c ON i.INS_CARRER =c.CAR_SEQ  
WHERE INS_ID ='thdalswjdrkdtk123';


UPDATE INSTRUCTOR
SET
INS_PW='$2a$10$ZN/5M4QAnhCB.H80kkYNfuA1SpXkYHQKiwimuSr/ytq74ezLRbwkne', 
INS_EMAIL='thdalswjd123@gmail.com', 
INS_PHONE='010-3355-0187', 
INS_BIRTH='1999-02-19', 
INS_PROFILE='송민정얼굴.jpg', 
INS_BANKNUM=1002559470001, 
INS_BANK='우리', 
INS_REGDATE=SYSDATE, 
INS_DELFLAG='H'
WHERE INS_ID='thdalswjdrkdtk123';